> ## Homework 3 - PageRank 
>
> ## Due Date: Oct. 29 (Friday), 23:00 SG Time
> ## Deliverables
> Save your notebook `ipynb` file as `StudentID_YourName_HW3.ipynb`, generate an `html` file from `ipynb` file and save as `StudentID_YourName_HW3.html`. Zip your notebook file, html file, and all your user-defined python files into a single `zip` file. 
>
> **Upload the `zip` file as `StudentID_YourName_HW3.zip`.** Please DO NOT include data file (Graph2021.txt) in your zip file.
>
> **Please make sure your code is executable.**
>
> ### HW3 has 90 points in total, which worths 9 points in the final assessment.

In [1]:
# Input your name and studentID
name = "Ong Jun Hong"
stuID = "A0202490R"

In [2]:
# Import libraries
import numpy as np
from scipy import sparse
import pandas as pd

beta = 0.87 # used in computing the PageRank

In [3]:
# load the Graph2021.txt and store it in variable "M"   (the loading can take you some time)
M = pd.read_csv('./Graph2021.txt', header=None)

# Converting M to a matrix
M = np.array(M)

In [4]:
# Output the number of rows and colums of data
rows, cols = M.shape
print('Matrix M has {} rows and {} columns.'.format(rows, cols))

Matrix M has 10001 rows and 10001 columns.


<div class="alert alert-warning">
<b>M is a square matrix contains only 0 and 1. $M_{ij}=1$ if and only if webpage j links to webpage i. The number of rows (or columns) of the matrix is the number of webpages in the network. You may want to store that number in a variable<b>
</div>

#### Each column of matrix M corresponds to one webpage in the network. For each column, divide each entry by the total number of outbound links of that webpage. Store the resulting matrix in "M2". Note that the graph may contain dead-end node. We will deal with this issue later.

In [5]:
# Check if there are any NaN in your matrix after the operation
# You can use np.isnan(your_matrix).any() to check. If there are NaNs, then you need to figure out why and fix it
num_outbound = M.sum(axis=0)
M2 = np.divide(M, num_outbound)

# Warning is generated as NaNs are introduced due to division by 0 (Dead-end nodes with outbound links).
print('Are there NaNs? {}'.format(np.isnan(M2).any()))
      
M2 = np.nan_to_num(M2, nan=0)

print('Are there NaNs? {}'.format(np.isnan(M2).any()))
print(M2)

<ipython-input-5-4015be473d5e>:4: RuntimeWarning: invalid value encountered in true_divide
  M2 = np.divide(M, num_outbound)


Are there NaNs? True
Are there NaNs? False
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


<div class="alert alert-info">
<b>Question 1 (20 points): Pre-process the matrix M2 to handle the "dead-end nodes". Store the new matrix as "H"</b> 
</div>

In [6]:
# H = M + 1/N * e * a^T
# Initialize vector e with length (N = cols) with all entries = 1.
e = np.ones(rows).reshape(-1, 1)

# Initialize vector a with entries = 1 if node is a "dead-end" node or 0 otherwise.
a = np.zeros(cols)
a[(num_outbound == 0)] = 1
a.reshape(-1, 1)

H = M2 + ((1/cols) * e * a.T)

print(H)
np.isnan(H).any()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


False

#### <u> Please output the 2726th entry of the 1st column of your matrix. </u> (5 points)

In [7]:
H[2725, 0]

0.1

#### <u> Please output the 1st entry of the 5th column of your matrix. </u> (5 points)

In [8]:
H[0, 4]

9.999000099990002e-05

In [9]:
# Generate matrix G using beta = 0.87. 
G = (beta * H) + ((1 - beta) * (1/rows) * e * e.T)

print(G)

[[1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]
 [1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]
 [1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]
 ...
 [1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]
 [1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]
 [1.29987001e-05 1.29987001e-05 1.29987001e-05 ... 1.29987001e-05
  1.29987001e-05 1.29987001e-05]]


In [10]:
# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank = ((1/rows) * np.ones(rows)).reshape(-1, 1)

print(PageRank)

[[9.9990001e-05]
 [9.9990001e-05]
 [9.9990001e-05]
 ...
 [9.9990001e-05]
 [9.9990001e-05]
 [9.9990001e-05]]


#### Raise matrix G to the 10th power and then multiply it by the initial PageRank vector. (10 points)  <u>Print the resulting PageRank vector and the runtime.</u>  (Hint: use the command %%time in the cell).

(You need to google how to raise a matrix to nth power and do matrix-vector multiplication). Check the run time of this computation.

This is supposed to run for some time so that in the subsequent questions, you will see the improvement due to other methods we mentioned in the lecture. <u> You are required to record the runtime of all six questions at the end of this homework. </u>

In [11]:
%%time

# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank = np.matmul(np.linalg.matrix_power(G, 10), PageRank)

print(PageRank)

[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 50 s


<div class="alert alert-info">
<b>Question 2 (10 points): Use "sparse.csr_matrix()" to transform your matrix H to a sparse matrix. Store the new matrix as "HS"</b> 
</div>

In [12]:
HS = sparse.csr_matrix(H)

#### Implement power iteration method for 10 iterations using the sparse matrix HS only. Initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph. <u>Print the PageRank vector after 10 iterations and the runtime.</u> (5 points)


In [13]:
%%time

# Implementing power iteration method shown in slide 50 of Lecture 8.

# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank = ((1/rows) * np.ones(rows)).reshape(-1, 1)

# Setting max iterations
T = 10
t = 1

# Initializing r0
r = [e / rows]

while True:
    print('Running iteration {}...'.format(t))
    
    r_t = r[-1]
    r_t1 = ((beta * HS) * r_t) + ((1 - beta) * r[0])
    r.append(r_t1)
    
    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = r[-1]
        break

    t += 1

print('Final PageRank vector:')
print(PageRank)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRank vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 119 ms


#### Redo this problem but use the matrix H instead of HS, <u> print the PageRank vector after 10 iterations and the runtime.</u> (5 points). Both of these two methods should be much faster than raising the matrix to the 10th power.You should be able to notice the runtime difference


In [14]:
%%time

# Implementing power iteration method shown in slide 50 of Lecture 8.

# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank = ((1/rows) * np.ones(rows)).reshape(-1, 1)

# Setting max iterations
T = 10
t = 1

# Initializing r0
r = [e / rows]

while True:
    print('Running iteration {}...'.format(t))
    
    r_t = r[-1]
    r_t1 = (np.matmul((beta * H), r_t)) + ((1 - beta) * r[0])
    r.append(r_t1)
    
    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = r[-1]
        break

    t += 1

print('Final PageRank vector:')
print(PageRank)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRank vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 3.13 s


#### Numpy is a very efficient implementation of matrix operations, you should be able to see substantial improvement in computation time compared with Q1.

<div class="alert alert-info">
<b>Question 3 (10 points): Use "sparse.csr_matrix()" to transform your matrix M2 to a sparse matrix. Store the new matrix as "MS". Implement the algorithm in slide 5 of Lecture 9 for 10 iterations. Do not preprocess the matrix M2 to get rid of the dead-end node issue. In this problem, you will have to solve this dead-end node issue during the iterations. You can either use for loop to go through all the websites one by one, or use matrix-vector operations</b> 
</div>

In [15]:
MS = sparse.csr_matrix(M2)

#### Initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph. <u> Print the PageRank vector after 10 iterations and the runtime. </u>

##### Matrix-Vector Multiplication Method

In [16]:
%%time

# Implementing power iteration method shown in slide 5 of Lecture 9.

# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank = ((1/rows) * np.ones(rows)).reshape(-1, 1)

# Setting max iterations
T = 10
t = 1

# Initializing r0
r = [e / rows]

while True:
    print('Running iteration {}...'.format(t))
    
    r_t = r[-1]
    r_hat_t1 = beta * MS.dot(r_t)
    S = np.matmul(e.T, r_hat_t1)
    r_t1 = r_hat_t1 + (((1 - S) /rows) * e)
    r.append(r_t1)
    
    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = r[-1]
        break

    t += 1
    
print('Final PageRange vector:')
print(PageRank)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRange vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 7.98 ms


#### If you use matrix-vector operations, the computational time for Q3 should be roughly the same as Q2. But this method does not require you to pre-process matrix M to solve the dead-end node issue 

<div class="alert alert-info">
<b>Question 4 (10 points): Transform the original matrix M into a table like data structure (could be dataframe or list or whatever) such that it has 2 columns: one is the label of the website; the other is the set of websites that are pointed by this website (i.e., the set of destination nodes). Note that for some rows, this set could be empty, in which case, it means the current website is a dead-end node in the graph </b> 
</div>

In [17]:
df = pd.DataFrame(columns=['Node', 'Destination Nodes'])

for j in range(cols):
    df.loc[j, 'Node'] = j
    df.at[j, 'Destination Nodes'] = np.argwhere(M[:, j] == 1).reshape(-1).tolist()

df.head()

Node                                  Destination Nodes
0    0  [2725, 2763, 3575, 4377, 6221, 7798, 7852, 801...
1    1  [137, 753, 1434, 2182, 3163, 3646, 3684, 3702,...
2    2                                  [473, 1843, 6748]
3    3  [67, 433, 537, 1068, 1118, 1191, 1236, 1953, 2...
4    4                                                 []

#### Implement the algorithm shown in slide 7 of lecture 9 using the table you have just created. <u> Print the PageRank vector after 10 iterations and the runtime. </u>

In [18]:
%%time

# initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpage in the graph
PageRank_old = e/rows
PageRank_new = np.zeros(rows).reshape(-1, 1)

# Setting max iterations
T = 10
t = 1

while True:
    print('Running iteration {}...'.format(t))
    
    for j in range(rows):
        destination_nodes = df.at[j, 'Destination Nodes']
        num_outbound = len(destination_nodes)
        
        # Skipping dead-end nodes
        if num_outbound == 0:
            continue
            
        for i in destination_nodes:
            PageRank_new[i] += beta * (PageRank_old[j] / num_outbound)

    S = np.matmul(e.T, PageRank_new)

    for j in range(rows):
        PageRank_new[j] = PageRank_new[j] + ((1 - S)/rows)
    
    PageRank_old = PageRank_new
    PageRank_new = np.zeros(rows).reshape(-1, 1)
    
    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = PageRank_new
        break
    
    t += 1

print('Final PageRange vector:')
print(PageRank_old)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRange vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 10.7 s


#### The computation time should be longer than Q3, but is still at the same scale. This is because the numpy's matrix operation is very efficient and our graph is still not that big

<div class="alert alert-info">
<b>Question 5 (20 points): Write a map-reduce code to compute the PageRanks for 10 iterations. Initialize the PageRank vector to be 1/N for all entries, where N is the total number of webpages in the graph. Do not use multiprocessing library for this problem </b> 
</div>

If there is warning saying "IOPub data rate exceeded in Jupyter notebook"

Need to launch Jupyter Notebook through Anaconda Prompt using:
jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10

In [19]:
# you may want to import the following libraries
import itertools
import collections

In [20]:
# Think carefully about how you will create a new table to express the graph
data = []

for j in range(rows):
    data.append([[df.loc[j, 'Node'], 1/rows], df.at[j, 'Destination Nodes']])

data[0]

[[0, 9.999000099990002e-05],
 [2725, 2763, 3575, 4377, 6221, 7798, 7852, 8014, 8753, 9575]]

#### Define your mapper and reducer function (10 points)

In [21]:
# define your mapper function
def mapper_PageRank(data):
    node = data[0][0]
    PageRank = data[0][1]
    destination = data[1]
    degree = len(destination)
    
    return[ [i, beta * PageRank/degree] for i in destination]
    
# define your reducer function
def reducer_PageRank(data):
    
    return (data[0], sum(data[1]))

In [22]:
# define other functions that you need

#### <u> Print the PageRank vector after 10 iterations and runtime. </u> (10 points)

In [23]:
%%time

# Setting max iterations
T = 10
t = 1

while True:
    print('Running iteration {}...'.format(t))
    
    mapped_values = map(mapper_PageRank, data)
    
    partition_value = list(itertools.chain(*mapped_values))
    
    partitioned_data = collections.defaultdict(list)
    for key, value in partition_value:
        partitioned_data[key].append(value)
    
    AT = map(reducer_PageRank, partitioned_data.items())
    AT = sorted(AT, key=lambda x: x[0])
    
    S = sum(AT[i][1] for i in range(rows))

    PageRank_new = [AT[i][1] + ((1-S)/rows) for i in range(rows)]

    for j in range(rows):
        data[j][0][1] = PageRank_new[j]

    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = PageRank_new
        break
    
    t += 1
    
PageRank = np.array(PageRank_new).reshape(-1, 1)
print('Final PageRange vector:')
print(PageRank)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRange vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 3.67 s


#### It should take more time to run than Q2---Q4. For a small graph like this one, the map-reduce framework is not as efficient as numpy. But it still should be faster than Q1

<div class="alert alert-info">
<b>Question 6 (20 points): Redo question 5 but use multiprocessing library for this problem.</b> 
</div>

If there is warning saying "IOPub data rate exceeded in Jupyter notebook"

Need to launch Jupyter Notebook through Anaconda Prompt using:
jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10

#### <u> Print the PageRank vector after 10 iterations and runtime. </u> 

In [24]:
import multiprocessing 
from multiprocessing import Pool
# import your functions. Note that in order to use the multiprocessing library, you need to save all of your user-defined 
# functions into a .py file and import here. If you directly use the functions you have defined in the previous question,
# it will run forever
import map_reduce

In [25]:
num_core = multiprocessing.cpu_count()
num_core

12

In [26]:
p = multiprocessing.Pool(num_core)

In [27]:
# Think carefully about how you will create a new table to express the graph
data = []

for j in range(rows):
    data.append([[df.loc[j, 'Node'], 1/rows], df.at[j, 'Destination Nodes']])

data[0]

[[0, 9.999000099990002e-05],
 [2725, 2763, 3575, 4377, 6221, 7798, 7852, 8014, 8753, 9575]]

In [28]:
%%time

# Setting max iterations
T = 10
t = 1

while True:
    print('Running iteration {}...'.format(t))
    
    mapped_values = p.map(map_reduce.mapper_PageRank, data)
    
    partition_value = list(itertools.chain(*mapped_values))
    
    partitioned_data = collections.defaultdict(list)
    for key, value in partition_value:
        partitioned_data[key].append(value)
    
    AT = p.map(map_reduce.reducer_PageRank, partitioned_data.items())
    AT = sorted(AT, key=lambda x: x[0])
    
    S = sum(AT[i][1] for i in range(rows))

    PageRank_new = [AT[i][1] + ((1-S)/rows) for i in range(rows)]

    for j in range(rows):
        data[j][0][1] = PageRank_new[j]

    # Stop condition
    if t >= T:
        print('Reached maximum iterations.\n\n')
        PageRank = PageRank_new
        break
    
    t += 1
    
PageRank = np.array(PageRank_new).reshape(-1, 1)
print('Final PageRange vector:')
print(PageRank)

Running iteration 1...
Running iteration 2...
Running iteration 3...
Running iteration 4...
Running iteration 5...
Running iteration 6...
Running iteration 7...
Running iteration 8...
Running iteration 9...
Running iteration 10...
Reached maximum iterations.


Final PageRange vector:
[[1.36319052e-04]
 [9.64711622e-05]
 [6.72644519e-05]
 ...
 [7.32876610e-05]
 [9.73028219e-05]
 [6.13970209e-05]]
Wall time: 4.52 s


#### It could be slower than Q5 but still faster than Q1. **Please do remember uploading the `py` files you created in this question.**

#### <u> Record the runtime of all six questions in the table below. </u> Please use the Wall Time with a unit (seconds/ms/...). Below is an example only for illustration.

| Question | Q1 | Q2 | Q3 | Q4 | Q5 | Q6 |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| Wall Time | 50s | 119ms(HS) 3.13s(H)| 7.98ms (Matrix-Vector) | 10.7s | 3.67s | 4.52s |
